services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      # - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
      # - ./nginx/logs:/var/log/nginx

  frontend:
    build: 
      context: ./frontend
      dockerfile: frontend.dockerfile

    # ports:
    #   - "3000:3000"
    volumes:
      - ./frontend:/code

  backend:
    depends_on:
      - db
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    env_file: 
      - ${ENV_FILE_PATH:-config.env}
    ports: 
      - 8080:80
    restart: always
    volumes:
      - ./backend/app:/app
  
  db:
    image: mariadb:latest
    env_file: 
      - ${ENV_FILE_PATH:-config.env}
    ports:
    - 3306:3306
    # volumes: 
    # - ./db/data:/var/lib/mysql