import Head from "next/head";
import Image from "next/image";
// import styles from '../styles/Home.module.css'
import Card from "../components/cards/Card";
import { useEffect } from "react";
import Cookies from "universal-cookie";
import Navbar from "../components/Navbars/Navbar";

export default function Home() {
  // cookieインスタンス
  // const cookies = new Cookies();

  return (
    <div className="layout-container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="main-section flex justify-center items-center">
        <h1 className="text-3xl">Amechii</h1>
      </div>
    </div>
  );
}
