import Head from "next/head";
import Image from "next/image";
// import styles from '../styles/Home.module.css'
import Card from "../components/cards/Card";
import { useEffect } from "react";
import Cookies from "universal-cookie";
import Navbar from "../components/Navbars/Navbar";
import * as cookie from 'cookie'

export default function Home(props) {

  console.log(props)

  const cookies = new Cookies();

  return (
    <div className="layout-container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="main-section flex justify-center items-center">
        <h1 className="text-3xl">Amechii</h1>
      </div>
    </div>
  );
}


export async function getServerSideProps(context) {

  if(!context.req.headers.cookie) {
    return {
      props: {
        data: null
      }
    }
  }

  const parsedCookies = cookie.parse(context.req.headers.cookie);
  const data = await fetch(`${process.env.NEXT_PUBLIC_RESTAPI_URL}api/v1/users/get-info`,{
    // mode: "no-cors",
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      Authorization: `${parsedCookies.token_type} ${parsedCookies.access_token}`,
    }
  })

  return {
    props: {
      // cookie: parsedCookies,
      data: JSON.parse(JSON.stringify(data))
    },
  };
}