import Head from "next/head";
import Image from "next/image";
// import styles from '../styles/Home.module.css'
import { useEffect, useContext } from "react";
import Navbar from "../components/Navbars/Navbar";
import { getUserData } from "../lib/users";
import { UserContext } from "../contexts/UserContext";

export default function Home(props) {
  const { userInfo, setUserInfo } = useContext(UserContext);

  useEffect(() => {
    if (props.data) {
      setUserInfo(props.data);
    }
  }, []);

  console.log(userInfo);

  return (
    <div className="layout-container">
      <Head>
        <title>Amechii</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="main-section flex justify-center items-center">
        <h1 className="text-3xl">Amechii</h1>
      </div>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const data = await getUserData(context);

  return {
    props: {
      data,
    },
  };
};
